# -*- coding:utf-8 -*-
"""B站直播弹幕 ASS 叠加

流程：
1. WBI 签名请求 getDanmuInfo 获取 token + host_list
2. ws:// 连接弹幕服务器，发送认证包（含 token + buvid）
3. 实时接收 DANMU_MSG → 写入 ASS → setSubtitles 刷新
"""
import struct
import json
import time
import threading
import os
import base64
import zlib
import random
import socket

import xbmc

from utils import getSetting, make_dirs

# ── ASS 生成 ──────────────────────────────────────────────────────────

def _fmt_ass_time(seconds):
    s = max(seconds, 0)
    return '%d:%02d:%02d.%02d' % (int(s//3600), int(s%3600//60), int(s%60), int(s*100)%100)

def _write_ass(path, danmaku_list, stay_time, font_size, alpha_hex, display_area):
    """display_area: 0.0～1.0，与 danmaku2ass 完全一致的样式"""
    width  = 1920
    height = 540
    outline = max(font_size / 25.0, 1)
    ao = str(int(outline))
    lines = [
        '[Script Info]',
        '; Script generated by plugin.video.bili live danmaku',
        'ScriptType: v4.00+',
        'PlayResX: %d' % width,
        'PlayResY: %d' % height,
        'Aspect Ratio: %d:%d' % (width, height),
        'Collisions: Normal',
        'WrapStyle: 2',
        'ScaledBorderAndShadow: yes',
        'YCbCr Matrix: TV.601',
        '',
        '[V4+ Styles]',
        'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, '
        'OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, '
        'ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, '
        'Alignment, MarginL, MarginR, MarginV, Encoding',
        'Style: R2L,sans-serif,%d,&H%sFFFFFF,&H%sFFFFFF,&H%s000000,'
        '&H%s000000,0,0,0,0,100,100,0.00,0.00,1,%s,0,7,0,0,0,0'
        % (font_size, alpha_hex, alpha_hex, alpha_hex, alpha_hex, ao),
        'Style: TOP,sans-serif,%d,&H%sFFFFFF,&H%sFFFFFF,&H%s000000,'
        '&H%s000000,0,0,0,0,100,100,0.00,0.00,1,%s,0,8,0,0,0,0'
        % (font_size, alpha_hex, alpha_hex, alpha_hex, alpha_hex, ao),
        'Style: BTM,sans-serif,%d,&H%sFFFFFF,&H%sFFFFFF,&H%s000000,'
        '&H%s000000,0,0,0,0,100,100,0.00,0.00,1,%s,0,2,0,0,0,0'
        % (font_size, alpha_hex, alpha_hex, alpha_hex, alpha_hex, ao),
        '', '[Events]',
        'Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text',
    ]
    for ts, text, mode, y in danmaku_list:
        safe = text.replace('{', '\\{').replace('}', '\\}')
        s = _fmt_ass_time(ts)
        e = _fmt_ass_time(ts + stay_time)
        if mode == 5:  # 顶部固定弹幕，不滚动
            lines.append(f'Dialogue: 0,{s},{e},TOP,,0,0,0,,{{\\an8\\pos(960,{y})}}{safe}')
        elif mode == 4:  # 底部固定弹幕，不滚动
            lines.append(f'Dialogue: 0,{s},{e},BTM,,0,0,0,,{{\\an2\\pos(960,{y})}}{safe}')
        else:  # 滚动弹幕，从右边缘平移到左边缘
            text_w = max(150, len(text) * font_size * 0.65)
            lines.append(
                f'Dialogue: 0,{s},{e},R2L,,0,0,0,,'
                f'{{\\move(1920,{y},{-int(text_w)},{y})}}{safe}')
    content = '\n'.join(lines)
    # 原子写入：先写 .tmp 再 rename，避免 Kodi 读到半截文件
    tmp = path + '.tmp'
    try:
        with open(tmp, 'w', encoding='utf-8') as f:
            f.write(content)
        os.replace(tmp, path)
    except Exception:
        try:
            os.remove(tmp)
        except Exception:
            pass


# ── WebSocket 工具 ────────────────────────────────────────────────────

def _ws_send(sock, data):
    """发送 WebSocket 二进制帧（client → server 需要 mask）"""
    if isinstance(data, str):
        data = data.encode('utf-8')
    frame = bytearray([0x82])  # FIN + binary
    length = len(data)
    if length < 126:
        frame.append(0x80 | length)
    elif length < 65536:
        frame.append(0x80 | 126)
        frame.extend(struct.pack('>H', length))
    else:
        frame.append(0x80 | 127)
        frame.extend(struct.pack('>Q', length))
    mask_key = os.urandom(4)
    frame.extend(mask_key)
    frame.extend(bytes(b ^ mask_key[i % 4] for i, b in enumerate(data)))
    sock.send(bytes(frame))


def _bili_packet(opcode, body=b''):
    """B站二进制协议包：16 字节头 + body"""
    if isinstance(body, str):
        body = body.encode('utf-8')
    return struct.pack('>IHHII', 16 + len(body), 16, 1, opcode, 1) + body


# ── 客户端 ────────────────────────────────────────────────────────────

class LiveDanmakuClient:
    def __init__(self, room_id, ass_path, uid=0, cookie='',
                 font_size=25, opacity=1.0, stay_time=8, display_area=1.0,
                 buvid=''):
        self.room_id      = int(room_id)
        self.ass_path     = ass_path
        self.uid          = int(uid) if uid else 0
        self._cookie      = cookie
        self._buvid       = buvid
        self.font_size    = int(font_size)
        self._opacity     = float(opacity)  # 0.0~1.0
        self._alpha_hex   = '%02X' % int(255 - self._opacity * 255)  # ASS 标准
        self.stay_time    = int(stay_time)
        self.display_area = float(display_area)

        self.running      = False
        self.sock         = None
        self.danmaku_list = []   # [(ts, text, mode, y), ...]
        self.lock         = threading.Lock()
        self._start_time  = 0

    def _get_token_wbi(self):
        """WBI 签名请求 getDanmuInfo"""
        try:
            from api import getWbiKeys, encWbi
            import requests
            params = encWbi({'id': str(self.room_id), 'type': '0'},
                            *getWbiKeys())
            full_url = 'https://api.live.bilibili.com/xlive/web-room/v1/index/getDanmuInfo'
            h = {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
                'Referer': 'https://live.bilibili.com/',
            }
            if self._cookie:
                h['Cookie'] = self._cookie
            r = requests.get(full_url, params=params, headers=h, timeout=10)
            data = r.json()
            xbmc.log('[live_danmaku] getDanmuInfo code=%s' % data['code'], xbmc.LOGINFO)
            if data['code'] == 0:
                return data['data']
        except Exception as e:
            xbmc.log('[live_danmaku] get_token_wbi: %s' % str(e), xbmc.LOGWARNING)
        return None

    def _connect(self, host, port):
        """ws:// TCP 直连"""
        try:
            sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            sock.settimeout(8)
            sock.connect((host, port))
            key = base64.b64encode(os.urandom(16)).decode()
            req = (f'GET /sub HTTP/1.1\r\nHost: {host}\r\n'
                   f'Upgrade: websocket\r\nConnection: Upgrade\r\n'
                   f'Sec-WebSocket-Key: {key}\r\n'
                   f'Sec-WebSocket-Version: 13\r\n\r\n')
            sock.send(req.encode())
            resp = b''
            while b'\r\n\r\n' not in resp:
                chunk = sock.recv(4096)
                if not chunk:
                    sock.close()
                    return None
                resp += chunk
            if b'101' not in resp:
                sock.close()
                return None
            self.sock = sock
            xbmc.log('[live_danmaku] ws connected %s:%s' % (host, port), xbmc.LOGINFO)
            return sock
        except Exception as e:
            xbmc.log('[live_danmaku] ws connect: %s' % str(e), xbmc.LOGWARNING)
            return None

    def _send_auth(self, token):
        body = json.dumps({
            'uid':      self.uid,
            'roomid':   self.room_id,
            'protover': 2,
            'buvid':    self._buvid or '',
            'platform': 'web',
            'type':     2,
            'key':      token,
        })
        _ws_send(self.sock, _bili_packet(7, body))
        xbmc.log('[live_danmaku] auth sent', xbmc.LOGINFO)

    def _alloc_position(self):
        """为滚动弹幕分配 y 坐标，避免与同轨道弹幕重叠。全部从右边缘 1920 进入"""
        canvas_h = 540
        y_max = max(1, int(canvas_h * self.display_area))
        row_h = max(self.font_size + 4, 30)
        rows = y_max // row_h
        if rows < 1:
            rows = 1
        now = time.time() - self._start_time
        occupied = set()
        for ts, _, mode, y in self.danmaku_list[-60:]:
            if mode in (1, 0, None) and now - ts < self.stay_time * 1.2:
                occupied.add(y // row_h)
        for _ in range(20):
            r = random.randint(0, rows - 1)
            if r not in occupied:
                break
        y = r * row_h + (row_h // 2)
        return y

    def _parse_binary(self, data):
        pos = 0
        while pos + 16 <= len(data):
            tl = struct.unpack_from('>I', data, pos)[0]
            hl = struct.unpack_from('>H', data, pos + 4)[0]
            pv = struct.unpack_from('>H', data, pos + 6)[0]
            op = struct.unpack_from('>I', data, pos + 8)[0]
            if tl < 16 or pos + tl > len(data):
                break
            body = data[pos + hl:pos + tl]
            pos += tl
            if pv == 2:
                try:
                    self._parse_binary(zlib.decompress(body))
                except zlib.error:
                    pass
                continue
            if op == 8:
                xbmc.log('[live_danmaku] auth OK (op=8)', xbmc.LOGINFO)
            elif op == 5:
                try:
                    msg = json.loads(body.decode('utf-8', errors='replace'))
                    if msg.get('cmd') == 'DANMU_MSG':
                        info = msg.get('info', [])
                        if len(info) >= 3:
                            meta = info[0]
                            mode = meta[1] if len(meta) > 1 else 1
                            ts = time.time() - self._start_time
                            with self.lock:
                                y = self._alloc_position()
                                self.danmaku_list.append(
                                    (ts, info[1], mode, y))
                except Exception:
                    pass

    def _recv_loop(self):
        buf = b''
        while self.running:
            try:
                self.sock.settimeout(1.0)
                chunk = self.sock.recv(4096)
                if not chunk:
                    break
                buf += chunk
                while len(buf) >= 2:
                    opcode = buf[0] & 0x0F
                    masked = (buf[1] & 0x80) != 0
                    plen   = buf[1] & 0x7F
                    offset = 2
                    if plen == 126:
                        if len(buf) < 4: break
                        plen = struct.unpack_from('>H', buf, offset)[0]
                        offset += 2
                    elif plen == 127:
                        if len(buf) < 10: break
                        plen = struct.unpack_from('>Q', buf, offset)[0]
                        offset += 8
                    if opcode == 0x8:
                        self.running = False
                        break
                    if masked:
                        if len(buf) < offset + 4 + plen: break
                        mk = buf[offset:offset + 4]
                        offset += 4
                        payload = bytes(buf[offset + i] ^ mk[i % 4] for i in range(plen))
                    else:
                        if len(buf) < offset + plen: break
                        payload = buf[offset:offset + plen]
                    offset += plen
                    buf = buf[offset:]
                    if opcode == 0x2:
                        self._parse_binary(payload)
                    elif opcode == 0x9:
                        try:
                            self.sock.send(bytes([0x8A, 0x00]))
                        except Exception:
                            pass
            except socket.timeout:
                continue
            except Exception as e:
                xbmc.log('[live_danmaku] recv: %s' % str(e), xbmc.LOGWARNING)
                break

    def _run(self):
        # 1. WBI 签名获取 token
        info = self._get_token_wbi()
        if not info:
            xbmc.log('[live_danmaku] getDanmuInfo FAIL', xbmc.LOGERROR)
            return

        token = info.get('token', '')
        host_list = info.get('host_list', [])
        if not host_list or not token:
            xbmc.log('[live_danmaku] no host/token', xbmc.LOGERROR)
            return

        # 用最后一个 host（wiliwili 做法）
        host = host_list[-1].get('host', '')
        port = host_list[-1].get('ws_port', 2244)
        xbmc.log('[live_danmaku] using %s:%s' % (host, port), xbmc.LOGINFO)

        # 2. ws:// 连接
        if not self._connect(host, port):
            return

        # 3. 发送认证
        self._send_auth(token)

        # 4. 心跳 + ASS 写入
        def _hb():
            while self.running and self.sock:
                time.sleep(30)
                if self.sock:
                    try:
                        _ws_send(self.sock, _bili_packet(2, b'[object Object]'))
                    except Exception:
                        pass
        threading.Thread(target=_hb, daemon=True).start()

        # 5. ASS 写入 + 刷新
        def _writer():
            last_sync = 0
            last_count = 0
            sync_count_delta = 0
            live_marker = '/live/' + str(self.room_id)
            while self.running:
                time.sleep(1.5)
                if not self.running:
                    break
                with self.lock:
                    count = len(self.danmaku_list)
                    if count == last_count:
                        continue
                    sync_count_delta += (count - last_count)
                    last_count = count
                    snapshot = list(self.danmaku_list[-600:])
                _write_ass(self.ass_path, snapshot, self.stay_time,
                           self.font_size, self._alpha_hex, self.display_area)
                if not self.running:
                    break
                now = time.time()
                if now - last_sync < 8 and sync_count_delta < 5:
                    continue
                last_sync = now
                sync_count_delta = 0
                try:
                    p = xbmc.Player()
                    if p.isPlaying():
                        cur = xbmc.getInfoLabel('Player.Filenameandpath') or ''
                        if live_marker in cur:
                            p.setSubtitles(self.ass_path)
                except Exception:
                    pass
        threading.Thread(target=_writer, daemon=True).start()

        self._start_time = time.time()
        self._recv_loop()

    def start(self):
        self.running = True
        threading.Thread(target=self._run, daemon=True).start()
        # 等待连接
        for _ in range(10):
            time.sleep(0.5)
            if not self.running:
                return False
            with self.lock:
                if self.danmaku_list:
                    return True
        return self.running

    def stop(self):
        self.running = False
        if self.sock:
            try:
                self.sock.close()
            except Exception:
                pass


# ── 便捷函数 ────────────────────────────────────────────────────────────

_instances = {}

def start_live_danmaku(room_id, uid=0, cookie=''):
    bp = xbmc.translatePath('special://temp/plugin.video.bili/')
    if not make_dirs(bp):
        return None, None
    path = os.path.join(bp, 'live_%s.ass' % room_id)

    # 获取 buvid
    buvid = ''
    try:
        from api import get_cookie_value
        buvid = get_cookie_value('buvid3')
    except Exception:
        pass

    # 占位 ASS（与 danmaku2ass 统一格式）
    ph = ('[Script Info]\n'
          '; Script generated by plugin.video.bili live danmaku\n'
          'ScriptType: v4.00+\n'
          'PlayResX: 1920\nPlayResY: 540\n'
          'Aspect Ratio: 1920:540\nCollisions: Normal\nWrapStyle: 2\n'
          'ScaledBorderAndShadow: yes\nYCbCr Matrix: TV.601\n\n'
          '[V4+ Styles]\n'
          'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, '
          'OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, '
          'ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, '
          'Alignment, MarginL, MarginR, MarginV, Encoding\n'
          'Style: R2L,sans-serif,25,&H00FFFFFF,&H00FFFFFF,&H00000000,'
          '&H00000000,0,0,0,0,100,100,0.00,0.00,1,1,0,7,0,0,0,0\n\n'
          '[Events]\n'
          'Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n'
          'Dialogue: 0,0:00:00.00,0:00:05.00,R2L,,0,0,0,,'
          '{\\move(1920,270,-150,270)}弹幕加载中...')
    try:
        with open(path, 'w', encoding='utf-8') as f:
            f.write(ph)
    except Exception:
        pass

    key = str(room_id)
    if key in _instances:
        try:
            _instances[key].stop()
        except Exception:
            pass

    c = LiveDanmakuClient(
        room_id, path, uid, cookie,
        float(getSetting('font_size')),
        float(getSetting('opacity')),
        float(getSetting('danmaku_stay_time')),
        float(getSetting('display_area')),
        buvid)
    ok = c.start()
    _instances[key] = c
    if not ok:
        xbmc.log('[live_danmaku] start FAIL for room=%s' % room_id, xbmc.LOGWARNING)
    return path, c

def stop_live_danmaku(room_id):
    key = str(room_id)
    if key in _instances:
        try:
            _instances[key].stop()
        except Exception:
            pass
        del _instances[key]

def stop_all_live_danmaku():
    """停止所有正在运行的直播弹幕线程"""
    for key in list(_instances.keys()):
        stop_live_danmaku(key)
